apiVersion: v1
kind: Service
metadata:
  name: mongo-service
spec:
  selector:
    app: mongo
  ports:
    - protocol: TCP
      port: 27017 #accessible by other services within the same cluster
      targetPort: 27017 #any traffic received by the Service on "port" will be forwarded to target port, on the MongoDB Pod
