apiVersion: v1
kind: Service
metadata:
  name: react-service
spec:
  type: LoadBalancer
  selector:
    app: react-server
  ports:
    - protocol: TCP
      port: 80 #accessible by other services within the same cluster
      targetPort: 80 #any traffic received by the Service on "port" will be forwarded to target port, in this case
                        # its 3500 as our server is listening in that port
      nodePort: 30010 #nodeport range from 30000 to 32000
