apiVersion: v1
kind: Service
metadata:
  name: node-service
spec:
  type: ClusterIP
  #type: NodePort just for testing the backend
  selector:
    app: node-server
  ports:
    - protocol: TCP
      port: 3500 #accessible by other services within the same cluster
      targetPort: 3500 #any traffic received by the Service on "port" will be forwarded to target port, in this case
                        # its 3500 as our server is listening in that port
      #nodePort: 30007 #nodeport range from 30000 to 32000, we only use nodeport with backedn for testing
