apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:
  mongo-user: bW9uZ291c2Vy #All strings must be in base64
  mongo-password: bW9uZ29wYXNzd29yZA==
  mongo-secret-key: ZXhhbXBsZQ==