apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-deployment
  labels:
    app: {{ .Values.appName }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
    spec:
      imagePullSecrets:
        - name: dockerhub-secret
      containers:
      - name: node-container
        image: "{{.Values.nodeImage.name}}:{{.Values.nodeImage.tag}}"
        ports:
        - containerPort: 3500
        env:
        - name: MONGO_USER
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: mongo-user
        - name: MONGO_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: mongo-password
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: mongo-secret-key
        - name: MONGO_URL
          valueFrom:
            configMapKeyRef:
              name: mongo-config
              key: mongo-url
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: node-service
  labels:
    job: node-api
    app: service-api
spec:
  selector:
    app: {{ .Values.appName }}
  ports:
    - name: node
      protocol: TCP
      port: 3500 #accessible by other services within the same cluster
      targetPort: 3500 #any traffic received by the Service on "port" will be forwarded to target port, in this case
                        # its 3500 as our server is listening in that port
      #nodePort: 30007 #nodeport range from 30000 to 32000, we only use nodeport with backedn for testing


