apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-deployment
  labels:
    app: {{.Values.frontendApp}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{.Values.frontendApp}}
  template:
    metadata:
      labels:
        app: {{.Values.frontendApp}}
    spec:
      imagePullSecrets:
        - name: dockerhub-secret
      containers:
      - name: react-container
        image: "{{.Values.reactImage.name}}:{{.Values.reactImage.tag}}"
        
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"

---

apiVersion: v1
kind: Service
metadata:
  name: react-service
spec:
  selector:
    app: {{.Values.frontendApp}}
  ports:
    - protocol: TCP
      port: 80 #accessible by other services within the same cluster
      targetPort: 80 #any traffic received by the Service on "port" will be forwarded to target port, in this case
                        # its 80 as our server is listening in that port
