apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: prometheus-custom-rule
  labels:
    release: prometheus #This is crucial so that prometheus find service monitors
spec:
  groups:
  - name: {{ .Values.appName }}
    rules:
      - alert: down
        expr: up == 0
        for: 0m
        labels:
          severity: critical
        annotations:
          summary: Prometheus target missing {{ .Values.appName }}