name: CI/CD Mern App

on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.20.7'

      - name: Install backend dependencies and run tests
        run: |
          cd app/backend
          npm install
          npm test

      - name: Install frontend dependencies and run build
        run: |
          cd app/frontend
          npm install
          npm run build
  docker:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push backend
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/private-devops:backend ./app/backend
          docker push ${{ secrets.DOCKER_USERNAME }}/private-devops:backend

      - name: Build & Push frontend
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/private-devops:frontend ./app/frontend
          docker push ${{ secrets.DOCKER_USERNAME }}/private-devops:frontend